spring.application.name=quickpoll

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://dpg-d3ce9q2li9vc73dg5cjg-a.oregon-postgres.render.com/quickpoll_zfmh
spring.datasource.username=quickpoll
spring.datasource.password=iMSUUsvLFlCs4WxCFNwzxSq9RFYeLVCV

# JPA/Hibernate Configuration
# 'update' will automatically update the schema based on your entities.
# Use 'validate' in production.
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements in the console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true